# Generated by Django 3.1.7 on 2021-05-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210513_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='county',
            field=models.CharField(default='county', max_length=40),
            preserve_default=False,
        ),
    ]
