# Generated by Django 3.1.7 on 2021-05-17 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.county'),
        ),
    ]
